stages:
  - deploy

.filter_script: &filter_script |
    git filter-branch --env-filter '
    if [["$GIT_AUTHOR_EMAIL" =~ "$GIT_COMMITTER_EMAIL" ]];
    then
        export GIT_COMMITTER_NAME="$CORRECT_NAME"
        export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
        export GIT_AUTHOR_NAME="$CORRECT_NAME"
        export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
    fi
    ' --tag-name-filter cat -- --branches --tags

.push_script: &push_script |
    for remote in `git branch -r`; \
    do \
      git push --force --tags origin HEAD:$(echo $remote | cut -d'/' -f2) -o ci.skip; \
    done  

before_script:
  - git remote set-url origin https://${CI_PUSH_TOKEN}:${CI_PUSH_TOKEN}@gitlab.com/$CI_PROJECT_PATH.git
  - git config --global user.email $CORRECT_EMAIL
  - git config --global user.name $CORRECT_NAME

change_authors:
  stage: deploy
  script:
    - *filter_script
    - *push_script
  only:
    - master
