stages:
  - deploy

.filter_script: &filter_script |
    git filter-branch --env-filter '
    OLD_EMAIL="jlcastrillon91@gmail.com"
    CORRECT_NAME="Harlow Fres"
    CORRECT_EMAIL="harlow.fres@gmail.com"
    if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
    then
        export GIT_COMMITTER_NAME="$CORRECT_NAME"
        export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
    fi
    if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
    then
        export GIT_AUTHOR_NAME="$CORRECT_NAME"
        export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
    fi
    ' --tag-name-filter cat -- --branches --tags

.push_script: &push_script |
    for remote in `git branch -r`; \
    do \
      git push --force --tags https://jlcastrillon91:Jenesaispas*1@github.com/jlcastrillon91/client-repository.git HEAD:$(echo $remote | cut -d'/' -f2) -o ci.skip; \
    done  

before_script:
  - git remote set-url origin https://jlcastrillon91:Jenesaispas*1@github.com/jlcastrillon91/client-repository.git
  - git config --global user.email 'harlow.fres@gmail.com'
  - git config --global user.name 'Harlow Fres'

change_authors:
  stage: deploy
  script:
    - *filter_script
    - *push_script
  only:
    - master
