before_script:
  - git remote set-url origin https://lovecraft:${CI_PUSH_TOKEN}@gitlab.com/dev-repository.git
  - git config --global user.email 'harlow.fres@gmail.com'
  - git config --global user.name 'Harlow Fres'

change_authors:
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  script:
    - sudo chmod +x change_authors.sh 
    - ./change_authors.sh
    - git push -f
