stages:
  - deploy

.filter_script: &filter_script |
    git filter-branch --env-filter '
    OLD_EMAIL="jlcastrillon91@gmail.com"
    CORRECT_NAME="Harlow Fres"
    CORRECT_EMAIL="harlow.fres@gmail.com"
    if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
    then
        export GIT_COMMITTER_NAME="$CORRECT_NAME"
        export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
    fi
    if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
    then
        export GIT_AUTHOR_NAME="$CORRECT_NAME"
        export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
    fi
    ' --tag-name-filter cat -- --branches --tags

before_script:
  - git remote set-url origin https://lovecraft:${CI_PUSH_TOKEN}@gitlab.com/lovecraft/dev-repository.git
  - git config --global user.email 'harlow.fres@gmail.com'
  - git config --global user.name 'Harlow Fres'
  - git config --add remote.origin.push '+refs/heads/*:refs/heads/*'
  - git config --add remote.origin.push '+refs/tags/*:refs/tags/*'

change_authors:
  stage: deploy
  script:
    - *filter_script
<<<<<<< HEAD
    - git push --force --all origin -o ci.skip
=======
    - git push --force origin HEAD:master -o ci.skip
>>>>>>> 4150cf79a4085cfc5c1e10d68aec8224ef3236c0
  only:
    - master

